config/routes.rb
Rails.application.routes.draw do

  root 'application#goodbye'

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end
  

end

app/models/blog/article.rb
class Blog::Article
  include ActiveModel::Model
  attr_accessor :title, :content, :created_at, :permalink, :author

  # Used for ATOM-feed id
   def id
     @permalink.to_i
   end

   def content
     remove_yaml_frontmatter_from @content
   end

   def excerpt
     content.split('<!--more-->').first
   end

   def has_more_text?
     content != excerpt
   end

   def created_at
     @created_at.to_date
   end

   def to_param
     @permalink.parameterize
   end

   # Query methods
   def self.all
     article_files.reverse.map do |file|
       self.new extract_data_from(file)
     end
   end

   def self.find_by_name(name)
     file = find_file_by(name)
     self.new extract_data_from(file)
   end

   private
   def self.article_files
     sort_by_id Dir.glob(articles_path + '/' + '*.md')
   end

   def self.sort_by_id(files)
     files.sort_by { |x| File.basename(x, '.*').to_i }
   end

   def self.find_file_by(name)
     id = article_files.index { |x| x =~ /#{name}.md/ }
     article_files[id]
   end

   def self.articles_path
     Rails.root.join('app', 'views', 'blog', 'published').to_s
   end

   # Content retrieval
   def self.extract_data_from(file)
     {
       content: File.read(file),
       permalink: File.basename(file, '.*')
     }.merge(yaml_frontmatter_metadata_from(file))
   end

   def self.yaml_frontmatter_metadata_from(file)
     YAML.load_file(file)
   end

   def remove_yaml_frontmatter_from(text)
     text.sub(/^\s*---(.*?)---\s/m, "")
   end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end


  def goodbye
      render text: "now feck off"
  end

end

app/controllers/blog/articles_controller.rb
# app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  def index
    @articles = Blog::Article.all
  end

  def show
    @article = Blog::Article.find_by_name(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

  def preserve_markdown(text) # Used to get the indentation right in the <pre> code blocks with Haml
    preserve markdown(text)
  end
end

app/views/blog/articles/_meta.html.haml
.meta
  %time{ pubdate: "", datetime: article.created_at }
    = l article.created_at, format: :long
  by
  = article.author

app/views/blog/articles/index.html.haml
- @articles.each do |article|
  %article
    %h1= link_to article.title, blog_article_path(article)
    = render partial: "meta", locals: { article: article }
    = preserve_markdown article.excerpt
    - if article.has_more_text?
      %p= link_to "Continue reading →", blog_article_path(article)

app/views/blog/articles/show.html.haml
%article
  %h1= @article.title
  = render partial: "meta", locals: { article: @article }
  = preserve_markdown @article.content
  %hr
  %p.action= link_to "← Back to Overview", blog_articles_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SonnieOnRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield